AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.6
      Handler: index.handler
      CodeUri: 
        Bucket: tobilee12
        Key: TransactionProcess2-a7d54be3-5b1c-4045-b26d-7a2ccdc482a3.zip
        MyS3Upload:
          Type: S3
          Properties:
            Bucke: !Ref MyS3Bucket
            Events: s3:ObjectCreated:*
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: goa3-upload
