version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::440393989684:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-13W0GE6X5TFDT"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::440393989684:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-7MYYMG6C6ZK1"
cloudformation_execution_role = "arn:aws:iam::440393989684:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1WYDLULNT3YP5"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1smze1tpot7ac"
image_repository = ""
CodeUri = "tobilee12"
region = "us-east-1"

[stage]
[stage.pipeline_bootstrap]
[stage.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::440393989684:role/aws-sam-cli-managed-stage-pi-PipelineExecutionRole-180B6D6AA0519"
cloudformation_execution_role = "arn:aws:iam::440393989684:role/aws-sam-cli-managed-stage-CloudFormationExecutionR-1L9EARK54CT48"
artifacts_bucket = "aws-sam-cli-managed-stage-pipelin-artifactsbucket-1cq9rz92xpjnf"
image_repository = ""
region = "us-east-1"
